apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow-dags
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadOnlyMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-dags
  namespace: airflow
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi