FROM python:3.10.5-slim

ARG src=./src/python/WebServer
ENV APP_PATH=/app
ENV AIRFLOW_HOST=airflow-webserver.airflow.svc.cluster.local:8080

WORKDIR ${APP_PATH}

COPY ${src} ./

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]